### ISSUE TITLE
SyntaxError when using LedgerAdapter

### ISSUE THREAD

**Issue by iicc1** [wavesplatform/waves-signature-adapter#44]
Hello, I'm trying to use the LedgerAdapter but I'm struggling to get it working.
This is my code:
```
import { LedgerAdapter } from '@waves/signature-adapter';

LedgerAdapter.getUserList().then(([userData]) => new LedgerAdapter(userData));
```
I compile this just to check if everything goes well so I can continue, but I get this weird error when I execute it:

```
/home/usuario/ledger-app/js/node_modules/@waves/waves-transactions/dist/transactions/mass-transfer.js:27
    seedsAndIndexes.forEach(([s, i]) => generic_1.addProof(tx, waves_crypto_1.signBytes(bytes, s), i));
                             ^

SyntaxError: Unexpected token [
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/usuario/ledger-app/js/node_modules/@waves/waves-transactions/dist/index.js:14:23)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
```

**Comment by tsigel** [comment]
How u build this code? 
U need initialize ledger options before get user list.

```
LedgerAdapter.initOptions({
    networkCode: 'W'.charCodeAt()
});
```
